[package]
name = "umem_grpc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
umem_proto = { workspace = true}
umem_controller = { workspace = true}
umem_core = { workspace = true}
anyhow = { workspace = true}
tracing = { workspace = true }

